name = "GeometricAlgebra"
uuid = "e5e1d9a6-e1f3-11e8-2670-81ea63d74a8d"
authors = ["MasonProtter <mason.protter@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"
